CREATE DATABASE global_electronic_retail;

USE global_electronic_retail;

SET GLOBAL LOCAL_INFILE = 1;

CREATE TABLE customers(
    CustomerKey INT,
    Gender varchar(10),
    Name VARCHAR(100),
    City VARCHAR(100),
    State_Code VARCHAR(10),
    State VARCHAR(100),
    Zip_Code INT,
    Country VARCHAR(100),
    Continent VARCHAR(50),
    Birthday DATE
);

CREATE TABLE sales(
    Order_Number INT,
    Line_Item INT,
    Order_Date DATE,
    Delivery_Date DATE,
    CustomerKey INT,
    StoreKey INT,
    ProductKey INT,
    Quantity INT,
    Currency_Code VARCHAR(10)
);

CREATE TABLE products(
    Product_Key INT PRIMARY KEY,
    Product_Name VARCHAR(100),
    Brand VARCHAR(100),
    Color VARCHAR(100),
    Unit_Cost_USD FLOAT,	
    Unit_Price_USD FLOAT,
    Subcategory_Key varchar(10),
    Subcategory VARCHAR(100),	
    CategoryKey varchar(10),
    Category VARCHAR(100)
);


CREATE TABLE stores (
    StoreKey INT PRIMARY KEY,	
    Country VARCHAR(100),	
    State VARCHAR(100),	
    Square_Meters INT,
    Open_Date DATE
);

LOAD DATA LOCAL INFILE 'D:/dataset/global_electronic_retailer/Customers.csv'
INTO TABLE customers
FIELDS TERMINATED BY ','
IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE 'D:/dataset/global_electronic_retailer/Sales.csv'
INTO TABLE customers
FIELDS TERMINATED BY ','
IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE 'D:/dataset/global_electronic_retailer/Products.csv'
INTO TABLE customers
FIELDS TERMINATED BY ','
IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE 'D:/dataset/global_electronic_retailer/Stores.csv'
INTO TABLE customers
FIELDS TERMINATED BY ','
IGNORE 1 ROWS;

-- This QUERY shows Revenue and profit generated by every product

SELECT
    p.Product_Name,
    p.Category,
    p.Unit_Cost_USD,
    p.Unit_Price_USD,
    SUM(s.Quantity) AS Total_Sold,
    SUM(s.Quantity * p.Unit_Price_USD) AS Total_Revenue,  
    SUM(s.Quantity * (p.Unit_Price_USD - p.Unit_Cost_USD)) AS Total_Profit  
FROM sales s
RIGHT JOIN products p ON s.ProductKey = p.Product_Key
GROUP BY p.Product_Name,p.Category, p.Unit_Cost_USD, p.Unit_Price_USD
ORDER BY Total_Profit desc;


-- This QUERY shows Revenue and profit generated by every store

SELECT
    st.StoreKey as store_key,
    st.Country as country,
    st.State as state,
    SUM(s.Quantity * p.Unit_Price_USD) AS Total_revenue,
    SUM(s.Quantity * (p.Unit_Price_USD - p.Unit_Cost_USD)) AS Total_profit
FROM stores st                                                         
LEFT JOIN sales s ON s.StoreKey = st.StoreKey
LEFT JOIN products p ON s.ProductKey = p.Product_key
GROUP BY st.StoreKey, st.Country, st.State
ORDER BY Total_Profit DESC;

-- This QUERY shows Revenue generated by Online store and Physical store

SELECT
CASE 
    WHEN s.`StoreKey` = 0 THEN 'online store' 
    ELSE  'physical stores'
END as store_status,
SUM(p.`Unit_Price_USD` * s.`Quantity`) AS revenue
from sales s 
LEFT JOIN products p ON s.`ProductKey` = p.`Product_Key`
GROUP BY store_status;

-- This Result Shows Which customer falls into which age group category

SELECT 
    s.`CustomerKey`,
    -- We use MAX(Order_Date) so we only calculate their age at their latest visit
    CASE 
        WHEN MAX(YEAR(s.`Order_Date`)) - YEAR(c.`Birthday`) <= 19 THEN 'Teen'
        WHEN MAX(YEAR(s.`Order_Date`)) - YEAR(c.`Birthday`) <= 35 THEN 'Young Adults'
        WHEN MAX(YEAR(s.`Order_Date`)) - YEAR(c.`Birthday`) <= 50 THEN 'Adult'
        WHEN MAX(YEAR(s.`Order_Date`)) - YEAR(c.`Birthday`) <= 65 THEN 'Middle Age'
        ELSE 'Senior'
    END AS age_group
FROM sales s
JOIN customers c ON s.`CustomerKey` = c.`CustomerKey`
-- Grouping by the Customer ensures absolute uniqueness
GROUP BY s.`CustomerKey`, c.`Birthday`
ORDER BY s.`CustomerKey`;

-- This QUERY shows Revenue generated by the customers by their loyalty status

WITH CustomerLoyalty AS (
       SELECT
        CustomerKey,
        COUNT(DISTINCT `Order_Number`) AS total_transactions
    FROM sales
    GROUP BY CustomerKey
)
SELECT
    CASE 
        WHEN cl.total_transactions = 1 THEN 'One-Hit Wonder'
        WHEN cl.total_transactions = 2 THEN 'Potential Loyalist' 
        ELSE 'Loyalist'
    END AS loyalty_status,
    
    COUNT(DISTINCT s.`CustomerKey`) AS total_customers,
    ROUND(SUM(p.`Unit_Price_USD` * s.`Quantity`), 2) AS total_revenue
FROM sales s
JOIN CustomerLoyalty cl ON s.`CustomerKey` = cl.CustomerKey
JOIN products p ON s.`ProductKey` = p.`Product_Key`
GROUP BY loyalty_status
ORDER BY total_revenue DESC;

-- This QUERY shows Revenue Generated by their Brand

SELECT
p.`Brand` AS brand,
SUM(p.`Unit_Price_USD` * s.`Quantity`) AS Revenue
FROM
sales s
JOIN products p ON s.`ProductKey` = p.`Product_Key`
GROUP BY brand
ORDER BY Revenue DESC;

-- This QUERY Shows the Revenue generated by their Category

SELECT
p.`Category` AS category,
SUM(p.`Unit_Price_USD` * s.`Quantity`) AS Revenue
FROM
sales s
JOIN products p ON s.`ProductKey` = p.`Product_Key`
GROUP BY category
ORDER BY Revenue DESC;
